"""student data

Revision ID: 8e5d541da6d9
Revises: 0fe3e0cafc73
Create Date: 2021-09-28 03:53:40.011476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e5d541da6d9'
down_revision = '0fe3e0cafc73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('major', sa.Text(), nullable=True))
    op.add_column('students', sa.Column('level', sa.Text(), nullable=True))
    op.add_column('students', sa.Column('age', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'age')
    op.drop_column('students', 'level')
    op.drop_column('students', 'major')
    # ### end Alembic commands ###
